name: LSDTT
channels:
- conda-forge
- defaults
dependencies:
- affine=2.1.0=py_1
- attrs=17.2.0=py27_0
- backports_abc=0.5=py27_0
- boto3=1.4.7=py27_0
- botocore=1.5.92=py27_0
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py27_0
- click=6.7=py27_0
- click-plugins=1.0.3=py27_0
- cligj=0.4.0=py27_0
- curl=7.49.1=vc9_2
- cycler=0.10.0=py27_0
- descartes=1.1.0=py27_0
- docutils=0.14=py27_0
- enum34=1.1.6=py27_1
- expat=2.1.0=vc9_3
- fiona=1.7.9=py27_0
- freetype=2.7=vc9_1
- freexl=1.0.2=vc9_2
- functools32=3.2.3.2=py27_1
- futures=3.1.1=py27_0
- gdal=2.2.0=np112py27_vc9_2
- geos=3.5.1=vc9_1
- hdf4=4.2.12=vc9_0
- hdf5=1.8.18=vc9_1
- hypothesis=3.23.0=py27_0
- icu=58.1=vc9_1
- jmespath=0.9.3=py27_0
- jpeg=9b=vc9_0
- kealib=1.4.7=vc9_2
- krb5=1.14.2=vc9_0
- libgdal=2.1.4=vc9_2
- libiconv=1.14=vc9_4
- libnetcdf=4.4.1.1=vc9_6
- libpng=1.6.28=vc9_1
- libpq=9.6.3=vc9_0
- libspatialite=4.3.0a=vc9_15
- libtiff=4.0.6=vc9_7
- libxml2=2.9.5=vc9_0
- matplotlib=2.0.2=py27_2
- munch=2.2.0=py27_0
- openjpeg=2.2.0=vc9_0
- openssl=1.0.2l=vc9_0
- pandas=0.20.3=py27_1
- pcre=8.39=vc9_0
- pip=9.0.1=py27_0
- proj4=4.9.3=vc9_4
- pympler=0.5=py27_0
- pyparsing=2.2.0=py27_0
- pyproj=1.9.5.1=py27_0
- pyqt=5.6.0=py27_4
- python=2.7.13=1
- python-dateutil=2.6.1=py27_0
- pytz=2017.2=py27_0
- qt=5.6.2=vc9_2
- rasterio=0.36.0=py27_0
- s3transfer=0.1.11=py27_0
- setuptools=36.3.0=py27_0
- shapely=1.6.1=py27_1
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_1
- six=1.10.0=py27_1
- snuggs=1.4.1=py27_0
- sqlite=3.13.0=vc9_1
- ssl_match_hostname=3.5.0.1=py27_1
- tornado=4.5.2=py27_0
- vc=9=0
- vs2015_runtime=14.0.25420=0
- wheel=0.29.0=py27_0
- wincertstore=0.2=py27_0
- xerces-c=3.1.4=vc9_3
- xz=5.2.3=0
- zlib=1.2.8=vc9_3
- mkl=2017.0.3=0
- numpy=1.12.1=py27_0
- scipy=0.19.1=np112py27_0
- vs2008_runtime=9.00.30729.5054=0
- zope=1.0=py27_0
- zope.interface=4.4.2=py27_0
- pip:
  - backports-abc==0.5
  - backports.ssl-match-hostname==3.5.0.1
prefix: C:\ProgramData\Miniconda2\envs\LSDTT

